configuration: 
  - Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -pre -y
  - cinst gitlink -Pre -y
  - if not exist gtk-sharp-2.12.26.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
  - msiexec /i gtk-sharp-2.12.26.msi /qn /norestart
  - if not exist gtk-sharp-2.99.3.msi appveyor DownloadFile https://download.gnome.org/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
  - msiexec /i gtk-sharp-2.99.3.msi /qn /norestart
  - cinst android-sdk

cache:
  - gtk-sharp-2.12.26.msi
  - gtk-sharp-2.99.3.msi

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - git submodule update --init --recursive
  - NuGet restore RoundedBoxView/RoundedBoxView.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - msbuild RoundedBoxView/RoundedBoxView.sln 

  
after_build:
  - NuGet pack RoundedBoxView\RoundedBoxView\RoundedBoxView.Forms.Plugin.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: Output
    name: RoundedBoxView-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'